spring:
  config:
    activate:
      on-profile:
        - test
  datasource:
    username: ${TEST_DB_USERNAME}
    password: ${TEST_DB_PASSWORD}
    url: jdbc:mysql://${TEST_DB_HOST}:${TEST_DB_PORT}/${TEST_DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver