spring:
  profiles:
    active:
      - test

  jpa:
    hibernate:
      ddl-auto: update

    show-sql:
      true

  servlet:
    multipart:
      enabled: true
      max-request-size:
        230MB
      max-file-size:
        200MB